enablePlugins(MicrobuilderPlay)

enablePlugins(MicrobuilderJs)

enablePlugins(PlayScala)

organization := "com.thoughtworks.microbuilder"

name := "sample"

libraryDependencies += "org.specs2" %% "specs2-core" % "3.6.4" % Test

routesGenerator := InjectedRoutesGenerator

val haxeJsFiles = taskKey[Seq[File]]("JavaScript files generated by Haxe")

haxeJsFiles := {
  val destinationDirectory = (sourceManaged in Assets).value
  val jsFileMappings = for {
    jsFile <- (haxe in Js).value
    mapping <- Seq(
      jsFile.getParentFile / raw"""${jsFile.getName}.map""" -> destinationDirectory / raw"""${jsFile.getName}.map""",
      jsFile -> destinationDirectory / jsFile.getName
    )
  } yield mapping
  IO.copy(jsFileMappings).toSeq
}

resourceGenerators in Assets <+= haxeJsFiles

libraryDependencies += "org.webjars.bower" % "browser-request" % "0.2.1"

haxeOptions in Js += "com.thoughtworks.microbuilder.js.JsOutgoingJsonService"

haxeOptions in Js += "-debug"
